repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. Must be aligned with the project's dependency in pyproject.toml.
    rev: v0.5.1
    hooks:
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
-   repo: local
    hooks:
    -   id: pytest-local
        name: Run Pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]
