# config.yaml.template
# Copy this file to config.yaml and fill in your values.
# DO NOT COMMIT config.yaml

registry:
  # Path to store trained models and metadata locally or on a mounted volume
  models_root_path: "/path/to/your/models/registry" # Example: /Users/yourname/dsba_models or ./models

azure:
  subscription_id: "YOUR_AZURE_SUBSCRIPTION_ID"
  resource_group_name: "dsba-mlops-rg"
  location: "WestEurope" # e.g., WestEurope, EastUS
  # ACI specific settings
  aci_cpu_cores: 1.0
  aci_memory_gb: 1.5
  # Storage for mounting config and models in ACI
  storage_account_name: "dsbastorageaccount"
  config_fileshare_name: "configshare"
  models_fileshare_name: "modelshare"

api_keys:
  # Placeholder for any external API keys if needed in the future

user_secrets:
  # Placeholder for user-specific sensitive info
